version: '3'

services:
  automation_cabinet:
    build: ./automation_cabinet/
    ports:
      - 8000:8000
    env_file: .env
    volumes:      
      - ./automation_cabinet:/app
      - static_volume:/app/staticfiles
  postgres:
    image: postgres:13
    env_file: .env
    volumes:
      - postgres-volume:/var/lib/postgresql/data
volumes:
  static_volume:
  postgres-volume: