--
-- PostgreSQL database dump
--

\restrict IMEBiLKZXtM9yVtj2aga6zLA1uO8mgfEc8zq31cwWNmciVEIEREL3jowdW3t7Ma

-- Dumped from database version 13.23 (Debian 13.23-1.pgdg13+1)
-- Dumped by pg_dump version 13.23 (Debian 13.23-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account_emailaddress; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.account_emailaddress (
    id integer NOT NULL,
    email character varying(254) NOT NULL,
    verified boolean NOT NULL,
    "primary" boolean NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.account_emailaddress OWNER TO postgres;

--
-- Name: account_emailaddress_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.account_emailaddress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_emailaddress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: account_emailconfirmation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.account_emailconfirmation (
    id integer NOT NULL,
    created timestamp with time zone NOT NULL,
    sent timestamp with time zone,
    key character varying(64) NOT NULL,
    email_address_id integer NOT NULL
);


ALTER TABLE public.account_emailconfirmation OWNER TO postgres;

--
-- Name: account_emailconfirmation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.account_emailconfirmation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_emailconfirmation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.authtoken_token OWNER TO postgres;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: elements_abr; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.elements_abr (
    id bigint NOT NULL,
    mass double precision NOT NULL,
    price double precision NOT NULL,
    name character varying(150) NOT NULL,
    "A" double precision NOT NULL,
    "B" double precision NOT NULL,
    "C" double precision NOT NULL,
    "Path" text NOT NULL,
    i double precision NOT NULL,
    fiksator_id bigint NOT NULL
);


ALTER TABLE public.elements_abr OWNER TO postgres;

--
-- Name: elements_abr_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.elements_abr ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.elements_abr_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: elements_automat; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.elements_automat (
    id bigint NOT NULL,
    mass double precision NOT NULL,
    price double precision NOT NULL,
    name character varying(150) NOT NULL,
    i double precision NOT NULL,
    "Phase" integer NOT NULL,
    "A" double precision NOT NULL,
    "B" double precision NOT NULL,
    "C" double precision NOT NULL,
    "Path" text NOT NULL,
    fiksator_id bigint NOT NULL
);


ALTER TABLE public.elements_automat OWNER TO postgres;

--
-- Name: elements_automat_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.elements_automat ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.elements_automat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: elements_cabinet; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.elements_cabinet (
    id bigint NOT NULL,
    mass double precision NOT NULL,
    price double precision NOT NULL,
    name character varying(150) NOT NULL,
    "A" double precision NOT NULL,
    "B" double precision NOT NULL,
    "C" double precision NOT NULL,
    "A_panel" double precision NOT NULL,
    "B_panel" double precision NOT NULL,
    "C_panel" double precision NOT NULL,
    "Path" text NOT NULL
);


ALTER TABLE public.elements_cabinet OWNER TO postgres;

--
-- Name: elements_cabinet_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.elements_cabinet ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.elements_cabinet_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: elements_contactor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.elements_contactor (
    id bigint NOT NULL,
    mass double precision NOT NULL,
    price double precision NOT NULL,
    name character varying(150) NOT NULL,
    i double precision NOT NULL,
    "Phase" integer NOT NULL,
    "A" double precision NOT NULL,
    "B" double precision NOT NULL,
    "C" double precision NOT NULL,
    "Path" text NOT NULL,
    fiksator_id bigint NOT NULL
);


ALTER TABLE public.elements_contactor OWNER TO postgres;

--
-- Name: elements_contactor_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.elements_contactor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.elements_contactor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: elements_fiksator; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.elements_fiksator (
    id bigint NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.elements_fiksator OWNER TO postgres;

--
-- Name: elements_fiksator_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.elements_fiksator ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.elements_fiksator_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_calculateresult; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_calculateresult (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    data jsonb NOT NULL,
    name_object character varying(1000),
    address_object character varying(1000),
    user_id bigint
);


ALTER TABLE public.users_calculateresult OWNER TO postgres;

--
-- Name: users_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    first_name character varying(100),
    last_name character varying(100),
    parent_name character varying(100),
    email character varying(250) NOT NULL,
    phone character varying(128),
    organization character varying(100),
    inn bigint,
    kpp bigint,
    city character varying(100),
    job_title character varying(100),
    agreement boolean NOT NULL,
    agreement_2 boolean NOT NULL
);


ALTER TABLE public.users_user OWNER TO postgres;

--
-- Name: users_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_user_groups OWNER TO postgres;

--
-- Name: users_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_user_user_permissions OWNER TO postgres;

--
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: account_emailaddress; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.account_emailaddress (id, email, verified, "primary", user_id) FROM stdin;
\.


--
-- Data for Name: account_emailconfirmation; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.account_emailconfirmation (id, created, sent, key, email_address_id) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add Token	6	add_token
22	Can change Token	6	change_token
23	Can delete Token	6	delete_token
24	Can view Token	6	view_token
25	Can add Token	7	add_tokenproxy
26	Can change Token	7	change_tokenproxy
27	Can delete Token	7	delete_tokenproxy
28	Can view Token	7	view_tokenproxy
29	Can add Модель шкафа	8	add_cabinet
30	Can change Модель шкафа	8	change_cabinet
31	Can delete Модель шкафа	8	delete_cabinet
32	Can view Модель шкафа	8	view_cabinet
33	Can add крепежа	9	add_fiksator
34	Can change крепежа	9	change_fiksator
35	Can delete крепежа	9	delete_fiksator
36	Can view крепежа	9	view_fiksator
37	Can add Модель контактора	10	add_contactor
38	Can change Модель контактора	10	change_contactor
39	Can delete Модель контактора	10	delete_contactor
40	Can view Модель контактора	10	view_contactor
41	Can add Модель автомата	11	add_automat
42	Can change Модель автомата	11	change_automat
43	Can delete Модель автомата	11	delete_automat
44	Can view Модель автомата	11	view_automat
45	Can add Модель АВР	12	add_abr
46	Can change Модель АВР	12	change_abr
47	Can delete Модель АВР	12	delete_abr
48	Can view Модель АВР	12	view_abr
49	Can add email address	13	add_emailaddress
50	Can change email address	13	change_emailaddress
51	Can delete email address	13	delete_emailaddress
52	Can view email address	13	view_emailaddress
53	Can add email confirmation	14	add_emailconfirmation
54	Can change email confirmation	14	change_emailconfirmation
55	Can delete email confirmation	14	delete_emailconfirmation
56	Can view email confirmation	14	view_emailconfirmation
57	Can add Группа	15	add_usergroup
58	Can change Группа	15	change_usergroup
59	Can delete Группа	15	delete_usergroup
60	Can view Группа	15	view_usergroup
61	Can add Пользователь	16	add_user
62	Can change Пользователь	16	change_user
63	Can delete Пользователь	16	delete_user
64	Can view Пользователь	16	view_user
65	Can add Результат расчета	17	add_calculateresult
66	Can change Результат расчета	17	change_calculateresult
67	Can delete Результат расчета	17	delete_calculateresult
68	Can view Результат расчета	17	view_calculateresult
\.


--
-- Data for Name: authtoken_token; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.authtoken_token (key, created, user_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-09-07 08:31:33.433945+00	2	Автоматический выключатель ВА 47-100 1P 100А (D) 10kA PROXIMA EKF	2	[]	11	1
2	2026-09-07 08:31:44.174163+00	2	Автоматический выключатель ВА 47-100 1P 100А (D) 10kA PROXIMA EKF	2	[{"changed": {"fields": ["\\u041f\\u0443\\u0442\\u044c \\u043a \\u0444\\u0430\\u0439\\u043b\\u0443"]}}]	11	1
3	2026-09-07 08:32:55.973893+00	2	Автоматический выключатель ВА 47-100 3P 100А (D) 10kA PROXIMA EKF	2	[{"changed": {"fields": ["\\u041d\\u0430\\u0437\\u0432\\u0430\\u043d\\u0438\\u0435", "\\u0428\\u0438\\u0440\\u0438\\u043d\\u0430"]}}]	11	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	authtoken	token
7	authtoken	tokenproxy
8	elements	cabinet
9	elements	fiksator
10	elements	contactor
11	elements	automat
12	elements	abr
13	account	emailaddress
14	account	emailconfirmation
15	users	usergroup
16	users	user
17	users	calculateresult
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-08-28 07:29:27.041248+00
2	contenttypes	0002_remove_content_type_name	2026-08-28 07:29:27.047714+00
3	auth	0001_initial	2026-08-28 07:29:27.126967+00
4	auth	0002_alter_permission_name_max_length	2026-08-28 07:29:27.131701+00
5	auth	0003_alter_user_email_max_length	2026-08-28 07:29:27.136422+00
6	auth	0004_alter_user_username_opts	2026-08-28 07:29:27.142021+00
7	auth	0005_alter_user_last_login_null	2026-08-28 07:29:27.147819+00
8	auth	0006_require_contenttypes_0002	2026-08-28 07:29:27.15187+00
9	auth	0007_alter_validators_add_error_messages	2026-08-28 07:29:27.158067+00
10	auth	0008_alter_user_username_max_length	2026-08-28 07:29:27.163591+00
11	auth	0009_alter_user_last_name_max_length	2026-08-28 07:29:27.169707+00
12	auth	0010_alter_group_name_max_length	2026-08-28 07:29:27.176088+00
13	auth	0011_update_proxy_permissions	2026-08-28 07:29:27.181885+00
14	auth	0012_alter_user_first_name_max_length	2026-08-28 07:29:27.187416+00
15	users	0001_initial	2026-08-28 07:29:27.274171+00
16	account	0001_initial	2026-08-28 07:29:27.329208+00
17	account	0002_email_max_length	2026-08-28 07:29:27.336189+00
18	account	0003_alter_emailaddress_create_unique_verified_email	2026-08-28 07:29:27.35649+00
19	account	0004_alter_emailaddress_drop_unique_email	2026-08-28 07:29:27.369445+00
20	account	0005_emailaddress_idx_upper_email	2026-08-28 07:29:27.381491+00
21	account	0006_emailaddress_lower	2026-08-28 07:29:27.390781+00
22	account	0007_emailaddress_idx_email	2026-08-28 07:29:27.4099+00
23	account	0008_emailaddress_unique_primary_email_fixup	2026-08-28 07:29:27.422234+00
24	account	0009_emailaddress_unique_primary_email	2026-08-28 07:29:27.435065+00
25	admin	0001_initial	2026-08-28 07:29:27.462832+00
26	admin	0002_logentry_remove_auto_add	2026-08-28 07:29:27.470281+00
27	admin	0003_logentry_add_action_flag_choices	2026-08-28 07:29:27.476635+00
28	authtoken	0001_initial	2026-08-28 07:29:27.502147+00
29	authtoken	0002_auto_20160226_1747	2026-08-28 07:29:27.52426+00
30	authtoken	0003_tokenproxy	2026-08-28 07:29:27.527872+00
31	authtoken	0004_alter_tokenproxy_options	2026-08-28 07:29:27.532324+00
32	elements	0001_initial	2026-08-28 07:29:27.596799+00
33	elements	0002_alter_abr_options	2026-08-28 07:29:27.601661+00
34	sessions	0001_initial	2026-08-28 07:29:27.622607+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
5od5e2koj6h29ve0ircenb5p6idui7hz	.eJxVjDEOwjAMRe-SGUW1qzQpIztniOzYIQWUSk07Ie4OlTrA-t97_2UibWuJW9MlTmLOBszpd2NKD607kDvV22zTXNdlYrsr9qDNXmfR5-Vw_w4KtfKtkXFEzSSSvIDjfnDEGrKCoqAbyAuSpw4TcecxJMk9jBpAlJx6MO8PE0Y5Dg:1wzr4x:GIzeLw-7bpLcEuQpNxMYLteiPG7G5KiNSF4cNvfx8XA	2026-09-11 07:32:47.281171+00
\.


--
-- Data for Name: elements_abr; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.elements_abr (id, mass, price, name, "A", "B", "C", "Path", i, fiksator_id) FROM stdin;
1	1.5	5000234230	Устройство автоматического ввода резерва CHINT АВР 100А NXZM-125S/3B (R)	312	223	178	авр/32A.glb	100	1
\.


--
-- Data for Name: elements_automat; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.elements_automat (id, mass, price, name, i, "Phase", "A", "B", "C", "Path", fiksator_id) FROM stdin;
1	0.1	500	Автоматический выключатель ВА 47-63N 1P 16А (C) 4,5 кА PROXIMA EKF	16	1	87.5	17.8	74.5	automat/16A.glb	2
3	0.1	289	Автоматический выключатель ВА 47-63N 1P 63А (C) 4,5 кА PROXIMA EKF	63	1	87.5	17.8	74.5	automat/63A.glb	2
4	0.1	217	Автоматический выключатель ВА 47-63N 1P 10А (C) 4,5 кА PROXIMA EKF	10	1	87.5	17.5	74.5	automat/10A.glb	2
6	0.1	230	Автоматический выключатель ВА 47-63N 1P 20А (C) 4,5 кА PROXIMA EKF	20	1	87.5	17.8	74.5	automat/20A.glb	2
7	0.1	308	Автоматический выключатель ВА 47-63N 1P 5А (C) 4,5 кА PROXIMA EKF	5	1	87.5	17.8	74.5	automat/5A.glb	2
8	0.1	289	Автоматический выключатель ВА 47-63N 1P 50А (C) 4,5 кА PROXIMA EKF	50	1	87.5	17.8	74.5	automat/50A.glb	2
9	0.176	1274	Автоматический выключатель ВА 47-100 1P 125А (C) 10kA PROXIMA EKF	125	1	83	27	72.7	automat/125A.glb	2
2	0.176	1037	Автоматический выключатель ВА 47-100 3P 100А (D) 10kA PROXIMA EKF	100	3	83	81	72.7	automat/BA 47-63N 3P 32А (C) 4,5 kA PROXIMA EKF.glb	2
\.


--
-- Data for Name: elements_cabinet; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.elements_cabinet (id, mass, price, name, "A", "B", "C", "A_panel", "B_panel", "C_panel", "Path") FROM stdin;
1	6.02	5240	ЩРНМ-1	400	300	200	362	232	13.9	shield/ЩРНМ-1.glb
2	14.73	10139	ЩРНМ-3	650	500	220	602	432	13.9	shield/ЩРНМ-3.glb
3	35	16533	ЩРНМ-5	1000	650	300	902	562	13.9	shield/ЩРНМ-5.glb
4	46	25119	ЩРНМ-6	1200	750	300	1102	662	13.9	shield/ЩРНМ-6.glb
\.


--
-- Data for Name: elements_contactor; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.elements_contactor (id, mass, price, name, i, "Phase", "A", "B", "C", "Path", fiksator_id) FROM stdin;
1	0.34	698	Контактор CHINT NC1-0910 9А 230В/АС3 1НО 50Гц	9	3	71	45.5	0	contactor/9A.glb	2
2	0.35	926	Контактор CHINT NC1-1810 18А 230В/АС3 1НО 50Гц	18	3	71	46.3	0	contactor/18A.glb	1
3	0.54	1211	Контактор CHINT NC1-2510 25А 230В/АС3 1НО 50Гц	25	3	80	56.6	0	contactor/25A.glb	1
4	0.55	1289	Контактор CHINT NXC-32 32А 220В/АС3 1НО+1НЗ 50Гц	32	3	81	56.6	0	contactor/32A.glb	1
\.


--
-- Data for Name: elements_fiksator; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.elements_fiksator (id, name) FROM stdin;
1	BOLT
2	DIN
\.


--
-- Data for Name: users_calculateresult; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_calculateresult (id, created_at, data, name_object, address_object, user_id) FROM stdin;
\.


--
-- Data for Name: users_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_user (id, password, last_login, is_superuser, username, is_staff, is_active, date_joined, first_name, last_name, parent_name, email, phone, organization, inn, kpp, city, job_title, agreement, agreement_2) FROM stdin;
1	pbkdf2_sha256$870000$z1TxoF85KaaQoytcBOp7x3$T3cKsMInyzeg19LdoWrZOSHBJ7BGDpYZ5pxGlJioRaI=	2026-08-28 07:32:47.277976+00	t	admin	t	t	2026-08-28 07:32:40.48376+00	\N	\N	\N	admin@m.ru	\N	\N	\N	\N	\N	\N	f	f
\.


--
-- Data for Name: users_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: users_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Name: account_emailaddress_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.account_emailaddress_id_seq', 1, false);


--
-- Name: account_emailconfirmation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.account_emailconfirmation_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 68, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 3, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 17, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 34, true);


--
-- Name: elements_abr_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.elements_abr_id_seq', 1, true);


--
-- Name: elements_automat_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.elements_automat_id_seq', 9, true);


--
-- Name: elements_cabinet_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.elements_cabinet_id_seq', 4, true);


--
-- Name: elements_contactor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.elements_contactor_id_seq', 4, true);


--
-- Name: elements_fiksator_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.elements_fiksator_id_seq', 2, true);


--
-- Name: users_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_user_groups_id_seq', 1, false);


--
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_user_id_seq', 1, true);


--
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_user_user_permissions_id_seq', 1, false);


--
-- Name: account_emailaddress account_emailaddress_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_pkey PRIMARY KEY (id);


--
-- Name: account_emailaddress account_emailaddress_user_id_email_987c8728_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_user_id_email_987c8728_uniq UNIQUE (user_id, email);


--
-- Name: account_emailconfirmation account_emailconfirmation_key_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirmation_key_key UNIQUE (key);


--
-- Name: account_emailconfirmation account_emailconfirmation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirmation_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: elements_abr elements_abr_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.elements_abr
    ADD CONSTRAINT elements_abr_pkey PRIMARY KEY (id);


--
-- Name: elements_automat elements_automat_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.elements_automat
    ADD CONSTRAINT elements_automat_pkey PRIMARY KEY (id);


--
-- Name: elements_cabinet elements_cabinet_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.elements_cabinet
    ADD CONSTRAINT elements_cabinet_pkey PRIMARY KEY (id);


--
-- Name: elements_contactor elements_contactor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.elements_contactor
    ADD CONSTRAINT elements_contactor_pkey PRIMARY KEY (id);


--
-- Name: elements_fiksator elements_fiksator_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.elements_fiksator
    ADD CONSTRAINT elements_fiksator_pkey PRIMARY KEY (id);


--
-- Name: users_calculateresult users_calculateresult_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_calculateresult
    ADD CONSTRAINT users_calculateresult_pkey PRIMARY KEY (id);


--
-- Name: users_user users_user_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_email_key UNIQUE (email);


--
-- Name: users_user_groups users_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_pkey PRIMARY KEY (id);


--
-- Name: users_user_groups users_user_groups_user_id_group_id_b88eab82_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_group_id_b88eab82_uniq UNIQUE (user_id, group_id);


--
-- Name: users_user users_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_permission_id_43338c45_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_permission_id_43338c45_uniq UNIQUE (user_id, permission_id);


--
-- Name: users_user users_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_username_key UNIQUE (username);


--
-- Name: account_emailaddress_email_03be32b2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_emailaddress_email_03be32b2 ON public.account_emailaddress USING btree (email);


--
-- Name: account_emailaddress_email_03be32b2_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_emailaddress_email_03be32b2_like ON public.account_emailaddress USING btree (email varchar_pattern_ops);


--
-- Name: account_emailaddress_user_id_2c513194; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_emailaddress_user_id_2c513194 ON public.account_emailaddress USING btree (user_id);


--
-- Name: account_emailconfirmation_email_address_id_5b7f8c58; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_emailconfirmation_email_address_id_5b7f8c58 ON public.account_emailconfirmation USING btree (email_address_id);


--
-- Name: account_emailconfirmation_key_f43612bd_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_emailconfirmation_key_f43612bd_like ON public.account_emailconfirmation USING btree (key varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: elements_abr_fiksator_id_10bc90f0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX elements_abr_fiksator_id_10bc90f0 ON public.elements_abr USING btree (fiksator_id);


--
-- Name: elements_automat_fiksator_id_9a1dd750; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX elements_automat_fiksator_id_9a1dd750 ON public.elements_automat USING btree (fiksator_id);


--
-- Name: elements_contactor_fiksator_id_7bf1952a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX elements_contactor_fiksator_id_7bf1952a ON public.elements_contactor USING btree (fiksator_id);


--
-- Name: unique_primary_email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX unique_primary_email ON public.account_emailaddress USING btree (user_id, "primary") WHERE "primary";


--
-- Name: unique_verified_email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX unique_verified_email ON public.account_emailaddress USING btree (email) WHERE verified;


--
-- Name: users_calculateresult_user_id_b9135ab3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_calculateresult_user_id_b9135ab3 ON public.users_calculateresult USING btree (user_id);


--
-- Name: users_user_email_243f6e77_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_email_243f6e77_like ON public.users_user USING btree (email varchar_pattern_ops);


--
-- Name: users_user_groups_group_id_9afc8d0e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_groups_group_id_9afc8d0e ON public.users_user_groups USING btree (group_id);


--
-- Name: users_user_groups_user_id_5f6f5a90; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_groups_user_id_5f6f5a90 ON public.users_user_groups USING btree (user_id);


--
-- Name: users_user_user_permissions_permission_id_0b93982e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_user_permissions_permission_id_0b93982e ON public.users_user_user_permissions USING btree (permission_id);


--
-- Name: users_user_user_permissions_user_id_20aca447; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_user_permissions_user_id_20aca447 ON public.users_user_user_permissions USING btree (user_id);


--
-- Name: users_user_username_06e46fe6_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_username_06e46fe6_like ON public.users_user USING btree (username varchar_pattern_ops);


--
-- Name: account_emailaddress account_emailaddress_user_id_2c513194_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_user_id_2c513194_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: account_emailconfirmation account_emailconfirm_email_address_id_5b7f8c58_fk_account_e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirm_email_address_id_5b7f8c58_fk_account_e FOREIGN KEY (email_address_id) REFERENCES public.account_emailaddress(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: elements_abr elements_abr_fiksator_id_10bc90f0_fk_elements_fiksator_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.elements_abr
    ADD CONSTRAINT elements_abr_fiksator_id_10bc90f0_fk_elements_fiksator_id FOREIGN KEY (fiksator_id) REFERENCES public.elements_fiksator(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: elements_automat elements_automat_fiksator_id_9a1dd750_fk_elements_fiksator_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.elements_automat
    ADD CONSTRAINT elements_automat_fiksator_id_9a1dd750_fk_elements_fiksator_id FOREIGN KEY (fiksator_id) REFERENCES public.elements_fiksator(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: elements_contactor elements_contactor_fiksator_id_7bf1952a_fk_elements_fiksator_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.elements_contactor
    ADD CONSTRAINT elements_contactor_fiksator_id_7bf1952a_fk_elements_fiksator_id FOREIGN KEY (fiksator_id) REFERENCES public.elements_fiksator(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_calculateresult users_calculateresult_user_id_b9135ab3_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_calculateresult
    ADD CONSTRAINT users_calculateresult_user_id_b9135ab3_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_group_id_9afc8d0e_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_group_id_9afc8d0e_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_user_id_5f6f5a90_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_5f6f5a90_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_perm_permission_id_0b93982e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_perm_permission_id_0b93982e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_20aca447_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_20aca447_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict IMEBiLKZXtM9yVtj2aga6zLA1uO8mgfEc8zq31cwWNmciVEIEREL3jowdW3t7Ma

