server {
  
  listen 80;
  index index.html index.htm;
  server_tokens off;
  


  location /static/models/ {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_pass http://automation_cabinet:8000/admin/;
  }

  
  location / {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_pass http://automation_cabinet:8000/;
  }

}