# Generated by Django 5.1.1 on 2026-06-18 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fiksator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Тип крепления')),
            ],
            options={
                'verbose_name': 'крепежа',
                'verbose_name_plural': 'крепежи',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Automat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('i', models.FloatField(verbose_name='Сила тока')),
                ('Phase', models.ImageField(upload_to='', verbose_name='Количество фаз')),
                ('A', models.FloatField(verbose_name='Высота')),
                ('B', models.FloatField(verbose_name='Ширина')),
                ('C', models.FloatField(verbose_name='Глубина')),
                ('Path', models.TextField(verbose_name='Путь к файлу')),
                ('fiksator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.fiksator')),
            ],
            options={
                'verbose_name': 'Модель автомата',
                'verbose_name_plural': 'Модели автоматов',
                'ordering': ('name',),
            },
        ),
    ]
