# Generated by Django 5.1.1 on 2026-07-28 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abr',
            options={'ordering': ('i',), 'verbose_name': 'Модель АВР', 'verbose_name_plural': 'Модели АВРов'},
        ),
    ]
