# Generated by Django 5.1.1 on 2026-06-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automat',
            name='mass',
            field=models.FloatField(default=0, verbose_name='Масса, кг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='automat',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена, руб'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='automat',
            name='Phase',
            field=models.IntegerField(verbose_name='Количество фаз'),
        ),
    ]
