# Generated by Django 5.1.1 on 2026-06-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_automat_mass_automat_price_alter_automat_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass', models.FloatField(verbose_name='Масса, кг')),
                ('price', models.FloatField(verbose_name='Цена, руб')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('A', models.FloatField(verbose_name='Высота')),
                ('B', models.FloatField(verbose_name='Ширина')),
                ('C', models.FloatField(verbose_name='Глубина')),
                ('Path', models.TextField(verbose_name='Путь к файлу')),
            ],
            options={
                'verbose_name': 'Модель шкафа',
                'verbose_name_plural': 'Модели шкафов',
                'ordering': ('name',),
            },
        ),
    ]
