# Generated by Django 5.1.1 on 2026-09-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_alter_abr_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='IP',
            field=models.FloatField(blank=True, null=True, verbose_name='Класс защиты'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='Visibility',
            field=models.TextField(blank=True, null=True, verbose_name='Видимость дверцы'),
        ),
    ]
