# Generated by Django 5.1.1 on 2026-06-18 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0003_cabinet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass', models.FloatField(verbose_name='Масса, кг')),
                ('price', models.FloatField(verbose_name='Цена, руб')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('i', models.FloatField(verbose_name='Сила тока')),
                ('Phase', models.IntegerField(verbose_name='Количество фаз')),
                ('A', models.FloatField(verbose_name='Высота')),
                ('B', models.FloatField(verbose_name='Ширина')),
                ('C', models.FloatField(verbose_name='Глубина')),
                ('Path', models.TextField(verbose_name='Путь к файлу')),
                ('fiksator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.fiksator')),
            ],
            options={
                'verbose_name': 'Модель контактора',
                'verbose_name_plural': 'Модели контакторов',
                'ordering': ('name',),
            },
        ),
    ]
