# Generated by Django 5.1.1 on 2026-09-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0004_alter_cabinet_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('A', models.FloatField(verbose_name='Высота')),
                ('B', models.FloatField(verbose_name='Ширина')),
                ('C', models.FloatField(verbose_name='Глубина')),
                ('Phase', models.IntegerField(verbose_name='Количество фаз')),
                ('mass', models.FloatField(verbose_name='Масса, кг')),
                ('Path', models.TextField(verbose_name='Путь к файлу')),
                ('price', models.FloatField(verbose_name='Цена, руб')),
            ],
            options={
                'verbose_name': 'Модель счетчика',
                'verbose_name_plural': 'Модели счетчиков',
                'ordering': ('name',),
            },
        ),
    ]
