# Generated by Django 5.1.1 on 2026-06-22 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0004_contactor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automat',
            options={'ordering': ('i',), 'verbose_name': 'Модель автомата', 'verbose_name_plural': 'Модели автоматов'},
        ),
        migrations.AlterModelOptions(
            name='cabinet',
            options={'ordering': ('i',), 'verbose_name': 'Модель шкафа', 'verbose_name_plural': 'Модели шкафов'},
        ),
        migrations.AlterModelOptions(
            name='contactor',
            options={'ordering': ('i',), 'verbose_name': 'Модель контактора', 'verbose_name_plural': 'Модели контакторов'},
        ),
        migrations.AddField(
            model_name='cabinet',
            name='i',
            field=models.FloatField(default=0, verbose_name='Сила тока'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ABR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass', models.FloatField(verbose_name='Масса, кг')),
                ('price', models.FloatField(verbose_name='Цена, руб')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('A', models.FloatField(verbose_name='Высота')),
                ('B', models.FloatField(verbose_name='Ширина')),
                ('C', models.FloatField(verbose_name='Глубина')),
                ('Path', models.TextField(verbose_name='Путь к файлу')),
                ('fiksator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.fiksator')),
            ],
            options={
                'verbose_name': 'Модель АВР',
                'verbose_name_plural': 'Модели АВРов',
                'ordering': ('name',),
            },
        ),
    ]
