# Generated by Django 5.1.1 on 2026-06-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0005_alter_automat_options_alter_cabinet_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abr',
            name='i',
            field=models.FloatField(default=0, verbose_name='Сила тока'),
            preserve_default=False,
        ),
    ]
