# Generated by Django 5.1.1 on 2026-10-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0005_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automat',
            name='Phase',
        ),
        migrations.AddField(
            model_name='abr',
            name='Phase',
            field=models.IntegerField(default=3, verbose_name='Количество фаз'),
            preserve_default=False,
        ),
    ]
