# Generated by Django 5.1.1 on 2026-10-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0006_remove_automat_phase_abr_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='automat',
            name='Phase',
            field=models.IntegerField(default=3, verbose_name='Количество фаз'),
            preserve_default=False,
        ),
    ]
